export default function useMovement() {
  const columnsMovement = [
    {
      name: 'solicitado_em',
      label: 'Solicitado em',
      field: 'solicitado_em',
      sortable: true,
    },
    {
      name: 'limitado_ate',
      label: 'Limitado até',
      field: 'limitado_ate',
      sortable: true,
    },
    {
      name: 'tipo',
      label: 'Tipo',
      field: 'tipo',
      sortable: true,
    },
    {
      name: 'cliente',
      label: 'Cliente',
      field: 'cliente',
      sortable: true,
    },
    {
      name: 'origem',
      label: 'Origem',
      field: 'origem',
    },
    {
      name: 'destino',
      label: 'Destino',
      field: 'destino',
    },
    {
      name: 'valor',
      label: 'Valor Movimentação R$',
      field: 'transactionValue',
      sortable: true,
      format: (val) =>
        `R$ ${val.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    },
    {
      name: 'status',
      label: 'Status',
      field: 'status',
    },
    {
      name: 'documentos',
      label: 'Documentos',
      field: 'documentos',
    },
    {
      name: 'actions',
      label: '',
      field: 'actions',
    },
  ]
  const rowsMovement = [
    {
      id: 1,
      solicitado_em: '10/04/2025 - 14:30',
      limitado_ate: '15/04/2025 - 23:59',
      tipo: 'Depósito',
      cliente: {
        name: 'Carlos Silva',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'carlos@gstrategyanalytics.com.br',
      },
      origem: 'Itaú',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 4500.0,
      status: 'Concluído: 10/04/2025 - 14:35',
      documentos: 'comprovante.pdf',
    },
    {
      id: 2,
      solicitado_em: '11/04/2025 - 09:15',
      limitado_ate: '16/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'Ana Oliveira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'ana@gstrategyanalytics.com.br',
      },
      origem: 'Bradesco',
      destino: 'Santander',
      destination: 'movimentar',
      transactionValue: 3200.5,
      status: 'Concluído: 11/04/2025 - 09:20',
      documentos: 'comprovante.pdf',
    },
    {
      id: 3,
      solicitado_em: '12/04/2025 - 16:45',
      limitado_ate: '17/04/2025 - 23:59',
      tipo: 'Saque',
      cliente: {
        name: 'Pedro Santos',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'pedro@gstrategyanalytics.com.br',
      },
      origem: 'Banco do Brasil',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 1500.0,
      status: 'Pendente',
      documentos: 'Sem anexo',
    },
    {
      id: 4,
      solicitado_em: '13/04/2025 - 11:20',
      limitado_ate: '18/04/2025 - 23:59',
      tipo: 'Saldo',
      cliente: {
        name: 'Mariana Costa',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'mariana@gstrategyanalytics.com.br',
      },
      origem: 'Nubank',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 7800.75,
      status: 'Concluído: 13/04/2025 - 11:25',
      documentos: 'extrato.pdf',
    },
    {
      id: 5,
      solicitado_em: '14/04/2025 - 13:10',
      limitado_ate: '19/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'João Pereira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'joao@gstrategyanalytics.com.br',
      },
      origem: 'Caixa Econômica',
      destino: 'Inter',
      destination: 'movimentar',
      transactionValue: 4200.5,
      status: 'Atrasado: 2 dias',
      documentos: 'Sem anexo',
    },
    {
      id: 6,
      solicitado_em: '15/04/2025 - 10:05',
      limitado_ate: '20/04/2025 - 23:59',
      tipo: 'Depósito',
      cliente: {
        name: 'Luiza Almeida',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'luiza@gstrategyanalytics.com.br',
      },
      origem: 'Santander',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 6300.25,
      status: 'Concluído: 15/04/2025 - 10:10',
      documentos: 'comprovante.pdf',
    },
    {
      id: 7,
      solicitado_em: '16/04/2025 - 15:30',
      limitado_ate: '21/04/2025 - 23:59',
      tipo: 'Saque',
      cliente: {
        name: 'Carlos Silva',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'carlos@gstrategyanalytics.com.br',
      },
      origem: 'Itaú',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 2000.0,
      status: 'Pendente',
      documentos: 'Sem anexo',
    },
    {
      id: 8,
      solicitado_em: '17/04/2025 - 08:45',
      limitado_ate: '22/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'Ana Oliveira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'ana@gstrategyanalytics.com.br',
      },
      origem: 'Bradesco',
      destino: 'Banco do Brasil',
      destination: 'movimentar',
      transactionValue: 5100.8,
      status: 'Concluído: 17/05/2025 - 08:50',
      documentos: 'comprovante.pdf',
    },
    {
      id: 9,
      solicitado_em: '18/04/2025 - 14:20',
      limitado_ate: '23/04/2025 - 23:59',
      tipo: 'Saldo',
      cliente: {
        name: 'Pedro Santos',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'pedro@gstrategyanalytics.com.br',
      },
      origem: 'Inter',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 9200.0,
      status: 'Concluído: 18/04/2025 - 14:25',
      documentos: 'extrato.pdf',
    },
    {
      id: 10,
      solicitado_em: '19/04/2025 - 11:15',
      limitado_ate: '24/04/2025 - 23:59',
      tipo: 'Depósito',
      cliente: {
        name: 'Mariana Costa',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'mariana@gstrategyanalytics.com.br',
      },
      origem: 'Nubank',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 3500.5,
      status: 'Concluído: 19/04/2025 - 11:20',
      documentos: 'identidade.jpg',
    },
    {
      id: 11,
      solicitado_em: '20/04/2025 - 16:40',
      limitado_ate: '25/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'João Pereira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'joaoa@gstrategyanalytics.com.br',
      },
      origem: 'Caixa Econômica',
      destino: 'Itaú',
      destination: 'movimentar',
      transactionValue: 2800.0,
      status: 'Atrasado: 1 dia',
      documentos: 'Sem anexo',
    },
    {
      id: 12,
      solicitado_em: '21/04/2025 - 09:25',
      limitado_ate: '26/04/2025 - 23:59',
      tipo: 'Saque',
      cliente: {
        name: 'Luiza Almeida',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'luiza@gstrategyanalytics.com.br',
      },
      origem: 'Santander',
      destino: 'N/A',
      destination: 'movimentar',
      transactionValue: 1200.0,
      status: 'Pendente',
      documentos: 'Sem anexo',
    },
  ]
  const getRowsMovement = (id) => {
    return rowsMovement.find((row) => row.id === id)
  }
  const getNameClients = (id = null) => {
    if (id) {
      const row = rowsMovement.find((row) => row.id === id)
      return [
        {
          value: row.id,
          label: row.cliente.name,
        },
      ]
    }
    // Se não passar o id, retorna todos os clientes
    return rowsMovement.map((row) => {
      return {
        value: row.id,
        label: row.cliente.name,
      }
    })
  }
  const tiposOptionsDeposito = [
    { value: 'deposit', label: 'Depósito' },
    { value: 'transferencia', label: 'Transferência' },
    { value: 'saque', label: 'Saque' },
    { value: 'saldo', label: 'Saldo' },
  ]
  const banks = [
    { label: 'Selecione uma opção', value: null },
    { label: 'Banco Inter', value: 'banco_inter' },
    { label: 'Banco Original', value: 'banco_original' },
    { label: 'Banco Pan', value: 'banco_pan' },
    { label: 'Banco Safra', value: 'banco_safra' },
    { label: 'Banco do Brasil', value: 'banco_do_brasil' },
    { label: 'Itaú', value: 'itau' },
    { label: 'Santander', value: 'santander' },
    { label: 'Caixa Econômica Federal', value: 'caixa' },
    { label: 'Banco do Nordeste', value: 'banco_do_nordeste' },
    { label: 'Banco da Amazônia', value: 'banco_da_amazonia' },
    { label: 'Banco Votorantim', value: 'banco_votorantim' },
    { label: 'Banco BMG', value: 'banco_bmg' },
    { label: 'Banco ModalMais', value: 'banco_modalmais' },
    { label: 'Banco Daycoval', value: 'banco_daycoval' },
    { label: 'Banco Fibra', value: 'banco_fibra' },
    { label: 'Banco Mercantil do Brasil', value: 'banco_mercantil_do_brasil' },
    { label: 'Banco Rendimento', value: 'banco_rendimento' },
    { label: 'Banco Indusval', value: 'banco_indusval' },
    { label: 'Banco Alfa', value: 'banco_alfa' },
    { label: 'Banco Bonsucesso', value: 'banco_bonsucesso' },
    { label: 'Banco C6 Bank', value: 'c6_bank' },
    { label: 'Banco Neon', value: 'banco_neon' },
    { label: 'Banco Agibank', value: 'banco_agibank' },
    { label: 'Banco Intermedium', value: 'banco_intermedium' },
    { label: 'Banco Original', value: 'banco_original' },
    { label: 'Banco Panamericano', value: 'banco_panamericano' },
    { label: 'Bradesco', value: 'bradesco' },
  ]
  return {
    columnsMovement,
    rowsMovement,
    getRowsMovement,
    getNameClients,
    tiposOptionsDeposito,
    banks,
  }
}
