import { useLayoutStore } from 'src/stores/layout'
import { storeToRefs } from 'pinia'

export default function useCliente() {
  const storeLayout = useLayoutStore()
  const { clientEdit } = storeToRefs(storeLayout)
  const columnsClient = [
    {
      name: 'cliente',
      required: true,
      label: 'Cliente',
      align: 'left',
      field: 'cliente',
      sortable: true,
    },
    {
      name: 'assessor',
      align: 'right',
      label: 'Assessor',
      field: 'assessor',
      sortable: true,
      headerStyle: 'text-align: end',
    },
    {
      name: 'saldo',
      align: 'right',
      label: 'Saldo Para Investir(R$)',
      field: 'saldo',
      sortable: true,
      headerStyle: 'text-align: end',
    },
    {
      name: 'contrato',
      align: 'right',
      label: 'Contratro (R$)',
      field: 'contrato',
      headerStyle: 'text-align: end',
    },
    {
      name: 'dividendo',
      align: 'right',
      label: 'Dividendo (R$)',
      field: 'dividendo',
      headerStyle: 'text-align: end',
    },
    { name: 'emprestimo', align: 'left', label: 'Empréstimo', field: 'emprestimo' },
    {
      name: 'actions',
      label: '',
      field: 'actions',
      headerStyle: 'width: 10px; text-align: end',
    },
  ]

  const rowsClient = [
    {
      id: 1,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Carlos Silva Nunes',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'carlos@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 2,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Ana Oliveira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'ana@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 3,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Pedro Santos',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'pedro@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 4,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Mariana Costa',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'mariana@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 5,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'João Pereira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/joao_default.png',
        email: 'joao@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 6,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Luiza Almeida',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'luiza@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 7,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Carlos Silva',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'carlos@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 8,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Ana Oliveira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'ana@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 9,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Pedro Santos',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'pedro@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
    {
      id: 10,
      newWeLend: {},
      level: 'A',
      weLend: [
        {
          status: 'Ativo',
          valor: 10000,
          data_loan: '01/01/2025',
          value_dividendo: 250.0,
          value_now_dividendo: 250.0,
          value_finish: 10000,
          value_before: 10000,
          number_parcelas: 12,
          date_payment: '01/02/2025',
          contrato: 'Contrato 1',
          vigencia: '31/12/2030',
          saldo: 5000,
        },
      ],
      investment: {
        classification: 'A',
        saldo: 150000,
        assessor: 1,
        data_dividendo: '21/02/2025',
        valor_dividendo: 250.0,
      },
      bank: {},
      residential: {},
      bankRegister: [
        {
          chave_pix: '123456789',
          cpf_cnpj: '123.456.789-00',
          name: 'Banco Exemplo',
          agency: '1234',
          account: '56789-0',
          type: 'Conta Corrente',
          status: 'Ativo',
        },
      ],
      cliente: {
        cpf_cnpj: '123.456.789-00',
        renda: 5000,
        profissao: 'Engenheiro',
        birth: '01/01/1990',
        name: 'Mariana Costa',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/_Avatar_.png',
        email: 'mariana@gstrategyanalytics.com.br',
      },
      assessor: 'Joe Doe',
      saldo: 210000,
      contrato: {
        total: 30000.0,
        quantity: '2 contratos',
      },
      dividendo: {
        total: 250.0,
        data: '31/01/2030',
      },
      emprestimo: 'Status',
    },
  ]

  const getClient = (id) => {
    const client = rowsClient.find((client) => client.id === id)
    if (client) {
      return {
        ...client,
      }
    }
    return null
  }

  const getClientIdName = (arrayRemove = []) => {
    let clientes = null

    if (arrayRemove.length > 0) {
      const lstCompare = arrayRemove.map((client) => client.id)
      clientes = rowsClient.filter((client) => !lstCompare.includes(client.id)) // Exclude clients based on the provided array
    } else {
      clientes = rowsClient.filter((client) => client.id !== clientEdit.value.id) // Exclude the current client being edited
    }

    const listClient = clientes.map((client) => ({
      id: client.id,
      name: client.cliente.name,
      avatar: client.cliente.avatar,
    }))
    return listClient
  }
  const getClientOptions = () => {
    return rowsClient.map((client) => ({
      label: client.cliente.name,
      value: client.id,
      avatar: client.cliente.avatar,
    }))
  }

  return {
    columnsClient,
    rowsClient,
    getClient,
    getClientIdName,
    getClientOptions,
  }
}
