export default function useMovement() {
  const columnsMovement = [
    {
      name: 'solicitado_em',
      label: 'Solicitado em',
      field: 'solicitado_em',
      sortable: true,
    },
    {
      name: 'limitado_ate',
      label: 'Limitado até',
      field: 'limitado_ate',
      sortable: true,
    },
    {
      name: 'tipo',
      label: 'Tipo',
      field: 'tipo',
      sortable: true,
    },
    {
      name: 'cliente',
      label: 'Cliente',
      field: 'cliente',
      sortable: true,
    },
    {
      name: 'origem',
      label: 'Origem',
      field: 'origem',
    },
    {
      name: 'destino',
      label: 'Destino',
      field: 'destino',
    },
    {
      name: 'valor',
      label: 'Valor Movimentação R$',
      field: 'valor',
      sortable: true,
      format: (val) =>
        `R$ ${val.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    },
    {
      name: 'status',
      label: 'Status',
      field: 'status',
    },
    {
      name: 'documentos',
      label: 'Documentos',
      field: 'documentos',
    },
  ]
  const rowsMovement = [
    {
      id: 1,
      solicitado_em: '10/04/2025 - 14:30',
      limitado_ate: '15/04/2025 - 23:59',
      tipo: 'Depósito',
      cliente: {
        name: 'Carlos Silva',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'carlos@gstrategyanalytics.com.br',
      },
      origem: 'Itaú',
      destino: 'N/A',
      valor: 4500.0,
      status: 'Concluído: 10/04/2025 - 14:35',
      documentos: 'comprovante.pdf',
    },
    {
      id: 2,
      solicitado_em: '11/04/2025 - 09:15',
      limitado_ate: '16/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'Ana Oliveira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'ana@gstrategyanalytics.com.br',
      },
      origem: 'Bradesco',
      destino: 'Santander',
      valor: 3200.5,
      status: 'Concluído: 11/04/2025 - 09:20',
      documentos: 'comprovante.pdf',
    },
    {
      id: 3,
      solicitado_em: '12/04/2025 - 16:45',
      limitado_ate: '17/04/2025 - 23:59',
      tipo: 'Saque',
      cliente: {
        name: 'Pedro Santos',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'pedro@gstrategyanalytics.com.br',
      },
      origem: 'Banco do Brasil',
      destino: 'N/A',
      valor: 1500.0,
      status: 'Pendente',
      documentos: 'Sem anexo',
    },
    {
      id: 4,
      solicitado_em: '13/04/2025 - 11:20',
      limitado_ate: '18/04/2025 - 23:59',
      tipo: 'Saldo',
      cliente: {
        name: 'Mariana Costa',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'mariana@gstrategyanalytics.com.br',
      },
      origem: 'Nubank',
      destino: 'N/A',
      valor: 7800.75,
      status: 'Concluído: 13/04/2025 - 11:25',
      documentos: 'extrato.pdf',
    },
    {
      id: 5,
      solicitado_em: '14/04/2025 - 13:10',
      limitado_ate: '19/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'João Pereira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'joao@gstrategyanalytics.com.br',
      },
      origem: 'Caixa Econômica',
      destino: 'Inter',
      valor: 4200.0,
      status: 'Atrasado: 2 dias',
      documentos: 'contrato.docx',
    },
    {
      id: 6,
      solicitado_em: '15/04/2025 - 10:05',
      limitado_ate: '20/04/2025 - 23:59',
      tipo: 'Depósito',
      cliente: {
        name: 'Luiza Almeida',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'luiza@gstrategyanalytics.com.br',
      },
      origem: 'Santander',
      destino: 'N/A',
      valor: 6300.25,
      status: 'Concluído: 15/04/2025 - 10:10',
      documentos: 'comprovante.pdf',
    },
    {
      id: 7,
      solicitado_em: '16/04/2025 - 15:30',
      limitado_ate: '21/04/2025 - 23:59',
      tipo: 'Saque',
      cliente: {
        name: 'Carlos Silva',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'carlos@gstrategyanalytics.com.br',
      },
      origem: 'Itaú',
      destino: 'N/A',
      valor: 2000.0,
      status: 'Pendente',
      documentos: 'Sem anexo',
    },
    {
      id: 8,
      solicitado_em: '17/04/2025 - 08:45',
      limitado_ate: '22/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'Ana Oliveira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'ana@gstrategyanalytics.com.br',
      },
      origem: 'Bradesco',
      destino: 'Banco do Brasil',
      valor: 5100.8,
      status: 'Concluído: 17/05/2025 - 08:50',
      documentos: 'comprovante.pdf',
    },
    {
      id: 9,
      solicitado_em: '18/04/2025 - 14:20',
      limitado_ate: '23/04/2025 - 23:59',
      tipo: 'Saldo',
      cliente: {
        name: 'Pedro Santos',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'pedro@gstrategyanalytics.com.br',
      },
      origem: 'Inter',
      destino: 'N/A',
      valor: 9200.0,
      status: 'Concluído: 18/04/2025 - 14:25',
      documentos: 'extrato.pdf',
    },
    {
      id: 10,
      solicitado_em: '19/04/2025 - 11:15',
      limitado_ate: '24/04/2025 - 23:59',
      tipo: 'Depósito',
      cliente: {
        name: 'Mariana Costa',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'mariana@gstrategyanalytics.com.br',
      },
      origem: 'Nubank',
      destino: 'N/A',
      valor: 3500.5,
      status: 'Concluído: 19/04/2025 - 11:20',
      documentos: 'identidade.jpg',
    },
    {
      id: 11,
      solicitado_em: '20/04/2025 - 16:40',
      limitado_ate: '25/04/2025 - 23:59',
      tipo: 'Transferência',
      cliente: {
        name: 'João Pereira',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'joaoa@gstrategyanalytics.com.br',
      },
      origem: 'Caixa Econômica',
      destino: 'Itaú',
      valor: 2800.0,
      status: 'Atrasado: 1 dia',
      documentos: 'contrato.docx',
    },
    {
      id: 12,
      solicitado_em: '21/04/2025 - 09:25',
      limitado_ate: '26/04/2025 - 23:59',
      tipo: 'Saque',
      cliente: {
        name: 'Luiza Almeida',
        avatar: 'https://sources.strategyanalytics.com.br/storage/users/default-avatar.png',
        email: 'luiza@gstrategyanalytics.com.br',
      },
      origem: 'Santander',
      destino: 'N/A',
      valor: 1200.0,
      status: 'Pendente',
      documentos: 'Sem anexo',
    },
  ]
  return {
    columnsMovement,
    rowsMovement,
  }
}
